FROM alpine:3.22.1
ARG BUILD_IMAGE_VERSION
LABEL org.opencontainers.image.version=${BUILD_IMAGE_VERSION}
LABEL org.opencontainers.image.title="smfc"
RUN apk add --no-cache ipmitool python3 py3-udev smartmontools curl
RUN ln -s /usr/sbin/ipmitool /usr/bin/ipmitool
RUN apk add --no-cache --virtual .depends py3-pip

COPY ./dist/smfc-${BUILD_IMAGE_VERSION}.tar.gz /
RUN pip install --prefix=/usr /smfc-${BUILD_IMAGE_VERSION}.tar.gz

RUN apk del .depends
ADD --chmod=755 docker/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
